server:
  port: 8080

spring:
  application:
    name: url-shortener
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/urlshortener?authSource=admin

app:
  base-url: http://localhost:8080
  short-code-length: 7
